### ISSUE TITLE
403 AccessDenied after refresh on route

### ISSUE THREAD

**Issue by chrisblackwell** [kpfefferle/ember-cli-deploy-cloudfront#20]
The plugin works great, but when I refresh my browser, when on a route, I get an AccessDenied. Not sure why this is being caused, as if I refresh on the same route directly accessing the S3 bucket URL, it works fine.

**Comment by kpfefferle** [comment]
Hi @chrisblackwell, here are a couple things I would check:

- If you're getting 403s instead of 404s on non-root routes, verify that your S3 bucket is set up for static site hosting and that you are using the static site endpoint (*not* the S3 bucket name) as the basis for your CloudFront distribution. The Static Website Hosting should return 404s instead of 403s.
- If you are getting a different result from CloudFront for a known asset (visiting the index at `/` or while serving up a fingerprinted asset) than what you get when using the static website endpoint, then it's most likely that CloudFront has cached an outdated response for that item. To remedy this, create a CloudFront invalidation to clear the cache for one or all (`*`) of the distribution routes so that CloudFront will re-check your bucket for the new data instead of returning its outdated cached response.

**Comment by chrisblackwell** [comment]
@kpfefferle The bucket thing was completely it. I got confused, and added the bucket name, rather then the S3 URL. Thank you for that suggestion 👍
